#!/usr/bin/env bash
#this file is to print best school 10 time and hi in index 9

i=1
while [ $i -le 10 ]
do
    echo "best school"
    if [ $i -eq 9 ]
    then
        echo "hi"
    fi
    ((i++))
done